spring:
  application:
    name: library-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        enabled: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/filehub?characterEncoding=utf-8&amp&serverTimezone=UTC&amp&useSSL=false
#  jpa:
#    hibernate:
#      ddl-auto: none
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  防止扫描到entity包中的JPA实体类（排序在前），暂时使用全类名引用实体类
#  type-aliases-package: com.example.filehub.commons.service.entity
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 18010
